import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import type { AppDefinition, RouteConfig } from './index.ts';

const loaderExport = /\bexport\s+(?:async\s+)?function\s+loader\s*\(/g;

export const remixRoutesId = 'virtual:flamefront/remix-routes';
const resolvedRemixRoutesId = `\0${remixRoutesId}`;
const deferredRouteId = 'virtual:flamefront/deferred-route';
const resolvedDeferredRoutePrefix = `\0${deferredRouteId}?entry=`;

export interface FlamefrontOptions {
	/** Project-root route manifest module. */
	readonly routes?: string;
}

function quote(value: string): string {
	return JSON.stringify(value);
}

function lazyLayout(entry: string): string {
	return `async () => { const routeModule = await import(${quote(entry)}); return { Component: routeModule.default }; }`;
}

function lazyRoute(entry: string, deferred: boolean): string {
	if (!deferred) {
		return `async () => { const routeModule = await import(${quote(entry)}); return { Component: routeModule.default, loader: import.meta.env.SSR ? routeModule.loader : loadRouteData }; }`;
	}

	const componentId = `${deferredRouteId}?entry=${encodeURIComponent(entry)}`;
	return `async () => { const [routeModule, componentModule] = await Promise.all([import(${quote(entry)}), import(${quote(componentId)})]); return { Component: componentModule.default, loader: import.meta.env.SSR ? routeModule.loader : loadRouteData }; }`;
}

function generateConfigs(configs: readonly RouteConfig[], depth = 1): string {
	const indent = '\t'.repeat(depth);
	const childIndent = '\t'.repeat(depth + 1);
	return configs
		.map((config) => {
			if ('children' in config) {
				return `${indent}{\n${childIndent}lazy: ${lazyLayout(config.entry)},\n${childIndent}children: [\n${generateConfigs(config.children, depth + 2)}\n${childIndent}],\n${indent}}`;
			}
			return `${indent}{\n${childIndent}path: ${quote(config.path)},\n${childIndent}lazy: ${lazyRoute(config.entry, config.hydration === 'deferred')},\n${childIndent}handle: { flamefront: ${JSON.stringify({ render: config.render, hydration: config.hydration })} },\n${indent}}`;
		})
		.join(',\n');
}

export function generateRemixRoutes(app: Pick<AppDefinition, 'routeTree'>): string {
	return `// Generated by Flamefront.\nimport { loadRouteData } from 'flamefront/remix-router/data';\n\nexport const routes = [\n${generateConfigs(app.routeTree)}\n];\n`;
}

export function generateDeferredRoute(entry: string): string {
	return `import { Hydrate } from 'octane';\nimport { interaction } from 'octane/hydration';\nimport Component from ${quote(entry)};\n\nexport default function DeferredRoute(props) @{\n\t<Hydrate when={interaction({ events: 'click' })}>\n\t\t<Component {...props} />\n\t</Hydrate>\n}\n`;
}

function findBodyStart(source: string, start: number): number {
	let parentheses = 0;
	for (let index = start; index < source.length; index += 1) {
		if (source[index] === '(') parentheses += 1;
		if (source[index] === ')') parentheses -= 1;
		if (source[index] === '{' && parentheses === 0) return index;
	}
	return -1;
}

function findBodyEnd(source: string, start: number): number {
	let depth = 0;
	let quote: '"' | "'" | '`' | null = null;
	let escaped = false;
	let lineComment = false;
	let blockComment = false;

	for (let index = start; index < source.length; index += 1) {
		const character = source[index];
		const next = source[index + 1];

		if (lineComment) {
			if (character === '\n') lineComment = false;
			continue;
		}
		if (blockComment) {
			if (character === '*' && next === '/') {
				blockComment = false;
				index += 1;
			}
			continue;
		}
		if (quote) {
			if (escaped) escaped = false;
			else if (character === '\\') escaped = true;
			else if (character === quote) quote = null;
			continue;
		}

		if (character === '/' && next === '/') {
			lineComment = true;
			index += 1;
			continue;
		}
		if (character === '/' && next === '*') {
			blockComment = true;
			index += 1;
			continue;
		}
		if (character === '"' || character === "'" || character === '`') {
			quote = character;
			continue;
		}
		if (character === '{') depth += 1;
		if (character === '}') {
			depth -= 1;
			if (depth === 0) return index + 1;
		}
	}

	return -1;
}

export function stripRouteLoader(source: string): string {
	loaderExport.lastIndex = 0;
	const match = loaderExport.exec(source);
	if (!match) return source;

	const bodyStart = findBodyStart(source, match.index);
	const bodyEnd = bodyStart < 0 ? -1 : findBodyEnd(source, bodyStart);
	if (bodyEnd < 0) throw new SyntaxError('Flamefront could not isolate the exported route loader.');

	const masked = source.slice(match.index, bodyEnd).replace(/[^\n\r]/g, ' ');
	return `${source.slice(0, match.index)}${masked}${source.slice(bodyEnd)}`;
}

export function flamefront(options: FlamefrontOptions = {}) {
	let root = process.cwd();
	let appPromise: Promise<AppDefinition> | undefined;
	let manifestRevision = 0;
	const manifestId = options.routes ?? '/src/routes.ts';
	const manifestPath = () => resolve(root, manifestId.startsWith('/') ? `.${manifestId}` : manifestId);
	const loadApp = async () => {
		const manifestUrl = new URL(pathToFileURL(manifestPath()));
		manifestUrl.searchParams.set('flamefront', String(manifestRevision));
		appPromise ??= import(manifestUrl.href).then((module) => {
			const app = module.app ?? module.default;
			if (!app?.routeTree) {
				throw new TypeError(`Flamefront route manifest ${manifestId} must export an app.`);
			}
			return app as AppDefinition;
		});
		return appPromise;
	};

	return {
		name: 'flamefront:route-modules',
		enforce: 'pre' as const,
		configResolved(config: { root: string }) {
			root = config.root;
		},
		handleHotUpdate(context: { file: string; server: { moduleGraph: { getModuleById(id: string): unknown; invalidateModule(module: unknown): void } } }) {
			if (context.file !== manifestPath()) return;
			manifestRevision += 1;
			appPromise = undefined;
			const generatedModule = context.server.moduleGraph.getModuleById(resolvedRemixRoutesId);
			if (generatedModule) context.server.moduleGraph.invalidateModule(generatedModule);
		},
		resolveId(id: string) {
			if (id === remixRoutesId) return resolvedRemixRoutesId;
			if (id.startsWith(`${deferredRouteId}?entry=`)) {
				return `${resolvedDeferredRoutePrefix}${id.slice(`${deferredRouteId}?entry=`.length)}.tsrx`;
			}
			return null;
		},
		async load(id: string) {
			if (id === resolvedRemixRoutesId) return generateRemixRoutes(await loadApp());
			if (id.startsWith(resolvedDeferredRoutePrefix)) {
				const encodedEntry = id.slice(resolvedDeferredRoutePrefix.length).replace(/\.tsrx$/, '');
				return generateDeferredRoute(decodeURIComponent(encodedEntry));
			}
			return null;
		},
		transform(source: string, id: string, options?: { ssr?: boolean }) {
			if (options?.ssr || !id.split('?', 1)[0].endsWith('.tsrx')) return null;
			const code = stripRouteLoader(source);
			return code === source ? null : { code, map: null };
		},
	};
}
